### ISSUE TITLE
Default testing script hits fid error

### ISSUE THREAD

**Issue by svenholcombe** [optimizers/logging4matlab#5]
Running any of the following lines creates an error:

```
logging.testspeed()
logging.testspeed(fullfile(pwd,'test.txt')) % When file doesn't exist
logging.testspeed(fullfile(pwd,'test.txt')) % When file exists
```

```
Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in logging.logging/writeLog (line 173)
        fprintf(self.logfid, logline);

Error in logging.logging/trace (line 94)
      self.writeLog(self.TRACE, caller_name, message);

Error in logging.testspeed (line 28)
    L.trace('test');
 
173         fprintf(self.logfid, logline);
```

There seems to be an initialisation error in that 

1. the fid is never properly set by the test function
2. the writeLog function attempts to fprintf to an fid that might not exist

![image](https://cloud.githubusercontent.com/assets/7341940/22476349/0562f5ea-e7b0-11e6-9c38-6876e8e55810.png)

**Comment by ragavsathish** [comment]
As logger object is a singleton instance, try clearing Matlab variables and run it with a valid file name. It worked for me.  

``` Matlab
>> clear all;
>> logging.testspeed('a.log')
```
